Algoritmo "atividade14_comandosDeDecisao"

Var
// Seção de Declarações das variáveis 
num1, num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("Escreva um número: ")
Leia (num1)
Escreva ("Escreva outro número: ")
Leia (num2)
Se (num1 < num2) Então
	Escreva ("O maior número é o:", num2)
Senao
	Escreva ("Os números digitados foram:", num1)
   Escreva (" e", num2)
FimSe

Fimalgoritmo