Algoritmo "funcaoMultiParam"
FUNCAO multi (x,y: inteiro): inteiro
Var
// Seção de Declarações das variáveis
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
retorne x * y
fimfuncao
var
n, m, res: inteiro
inicio
escreval ("Digite o primeiro número: ")
leia (n)
escreval ("Agora, digite o segundo número: ")
leia (m)
res <- multi(n,m)
escreva ("O resultado da multiplicação é: ", res)
Fimalgoritmo