Algoritmo "funcaoSemParametro"
FUNCAO multi: inteiro
Var
// Seção de Declarações das variáveis
aux: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
aux <- n * m
retorne aux
fimfuncao
var
n, m: inteiro
res: inteiro
inicio
escreval ("Digite o primeiro número: ")
leia (n)
escreval ("Agora, digite o segundo número: ")
leia (m)
res <- multi
escreva ("O resultado da multiplicação é: ", res)
Fimalgoritmo