Algoritmo "tipoDado"

Var
// Seção de Declarações das variáveis 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Nome: Flávia.")
Escreval ("   Tipo literal com 6 caracteres")
Escreval ("Idade:", 17)
Escreval ("   Tipo numérico inteiro positivo")
Escreval ("Altura:", 1.57)
Escreval ("   Tipo numérico real com 2 casas decimais")
Escreval ("Criança:", Verdadeiro)
Escreval ("   Tipo lógico booleano")

Fimalgoritmo